working on gigpost controllers, with this commit the status is not sh…
wyncode/C40_turntable_gigs pull request #10
Opened 2020-12-15 01:26 UTC by leriche03

…owing any errors in terminal but the api can not connect using postman

2020-12-15 14:28 UTC, leopolicastro requested changes

2020-12-15 14:28 UTC, leopolicastro commented on server/controllers/gigPost.js
> +    res.send(doc);
Any reason why we used `.send()` here and `.json()` in the others?  `.send()` is used more for server-side rendering.  Since we are using React for our front end we're not really using Express for SSR so we usually just send it back as `.json()` to make it easy for React to parse it.  `.send()` is fine for the error handling, I'm talking more about `res.send(doc);`.

2020-12-15 14:28 UTC, leopolicastro commented on server/controllers/gigPost.js
> +const gigPost = require('../db/models/gigPost');
Here you are requiring the Model lowercased but in line 4 you use it capitalized, this will throw an error.

2020-12-15 14:28 UTC, leopolicastro commented on server/controllers/gigPost.js
> +  Post.findByIdAndRemove(req.params.id, function (err, gigPost) {
Where is `Post` coming from, does this run?

2020-12-17 02:07 UTC, leriche03 commented on server/controllers/gigPost.js
> +    res.send(doc);
ahhh, that makes sense will make those changes asap.

2020-12-17 02:15 UTC, leriche03 reviewed
fixed gig post controllers( this current version has the key properties for the updateGigPost function hardcoded plan to change in stretch goal)

2020-12-18 21:01 UTC, leopolicastro approved these changes

2020-12-18 21:01 UTC, leopolicastro commented on server/app.js
> +  gigRouter = require('./routes/secure/gigPost');
Swap out the semi colon in line 6 for a comma

2020-12-18 21:23 UTC, merged